name: Server Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Use Composer
        run: composer install
      - name: FTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with: 
          server: arturscibor.pl
          username: artur
          password: ${{ secrets.password }}
          local_path: ./*
          remote_path: /var/www/ProjektInzynierski/projektinzynierski.server.arturscibor.pl/
          port: 22
          sftp_only: true
